### ISSUE TITLE
Github actions possibly breaking synch scripts between GH and on-prem version control

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#5367]
```
 ! [remote rejected] dbstash/waltz-5319-auth-source-panel-svelte -> db-contrib/waltz-5319-auth-source-panel-svelte (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/maven.yml` without `workflow` scope)
```

Intention is to delete the maven.yml whilst we invesigate.

The .yml file is here:

```
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Waltz H2


    
    
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup postgres
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: waltz
        postgresql user: postgres
        
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Cache Maven packages    
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
          
    - name: Build with Maven
      run: mvn -B -s .build.settings.xml -Pbuild-h2,waltz-h2 clean package;
```

Guessing we need to say that we only run on the `finos/waltz` fork.  Not other forks.
